# Generated by Django 4.0 on 2021-12-31 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='tekst')),
                ('link', models.URLField(verbose_name='lenkjepeikar')),
                ('order', models.FloatField(verbose_name='rekkjefølgje')),
                ('type', models.CharField(choices=[('LINK', 'lenkje'), ('DROPDOWN', 'nedfallsmeny')], default='LINK', max_length=255, verbose_name='type')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='navbar.navbaritem')),
            ],
            options={
                'verbose_name': 'navigasjonslineelement',
                'verbose_name_plural': 'navigasjonslineelement',
            },
        ),
    ]
