# Generated by Django 4.0 on 2021-12-31 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbaritem',
            options={'ordering': ['order', 'text'], 'verbose_name': 'navigasjonslineelement', 'verbose_name_plural': 'navigasjonslineelement'},
        ),
    ]
