# Generated by Django 4.0 on 2021-12-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0002_alter_navbaritem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbaritem',
            name='link',
            field=models.CharField(max_length=255, verbose_name='lenkjepeikar'),
        ),
    ]
