# Generated by Django 4.0 on 2021-12-31 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0003_alter_navbaritem_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbaritem',
            options={'ordering': ['order', 'text'], 'verbose_name': 'navigasjonslinepunkt', 'verbose_name_plural': 'navigasjonslinepunkt'},
        ),
        migrations.AlterField(
            model_name='navbaritem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='navbar.navbaritem', verbose_name='underpunkt av'),
        ),
    ]
