# Generated by Django 4.0 on 2022-01-05 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('navbar', '0006_alter_navbaritem_options_alter_navbaritem_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbaritem',
            name='link',
            field=models.CharField(blank=True, max_length=255, verbose_name='lenkjepeikar'),
        ),
        migrations.CreateModel(
            name='NavbarItemPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='navbar.navbaritem', verbose_name='navigasjonslinepunkt')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navbar_items', to='auth.permission', verbose_name='tilgjenge')),
            ],
            options={
                'verbose_name': 'navigasjonslinepunkttilgjenge',
                'verbose_name_plural': 'navigasjonslinepunkttilgjenge',
            },
        ),
    ]
