# Generated by Django 4.0 on 2022-01-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('navbar', '0007_alter_navbaritem_link_navbaritempermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarItemPermissionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requirements', to='navbar.navbaritem', verbose_name='navigasjonslinepunkt')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navbar_items', to='auth.permission', verbose_name='tilgjenge')),
            ],
            options={
                'verbose_name': 'navigasjonslinepunkttilgjengekrav',
                'verbose_name_plural': 'navigasjonslinepunkttilgjengekrav',
            },
        ),
        migrations.DeleteModel(
            name='NavbarItemPermission',
        ),
    ]
