# Generated by Django 4.0 on 2022-01-05 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('navbar', '0008_navbaritempermissionrequirement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbaritempermissionrequirement',
            options={'verbose_name': 'navigasjonslinepunktløyvekrav', 'verbose_name_plural': 'navigasjonslinepunktløyvekrav'},
        ),
        migrations.AlterField(
            model_name='navbaritempermissionrequirement',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navbar_items', to='auth.permission', verbose_name='løyve'),
        ),
    ]
