# Generated by Django 3.2.7 on 2021-09-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'kommentar', 'verbose_name_plural': 'kommentarar'},
        ),
    ]
