# Generated by Django 4.0.1 on 2022-01-13 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def ensure_filename_original(apps, schema_editor):
    Comment = apps.get_model("comments", "Comment")
    for comment in Comment.objects.all():
        comment.modified_by = comment.created_by
        comment.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_alter_comment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='submitted',
            new_name='created',
        ),
        migrations.AddField(
            model_name='comment',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='redigert'),
        ),
        migrations.AddField(
            model_name='comment',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='redigert av'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='laga av'),
        ),
        migrations.RunPython(ensure_filename_original),
    ]
