# Generated by Django 4.0.1 on 2022-01-13 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0003_rename_submitted_comment_created_comment_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='redigert av'),
        ),
    ]
