# Generated by Django 4.0.2 on 2022-02-10 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_comment_modified_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'created', 'verbose_name': 'kommentar', 'verbose_name_plural': 'kommentarar'},
        ),
    ]
