# Generated by Django 4.0.2 on 2022-02-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_pk',
            field=models.IntegerField(),
        ),
    ]
