# Generated by Django 4.0.2 on 2022-02-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_alter_comment_object_pk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'created', 'ordering': ['created'], 'verbose_name': 'kommentar', 'verbose_name_plural': 'kommentarar'},
        ),
    ]
