# Generated by Django 3.0.2 on 2020-03-06 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import julekalender.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Julekalender',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('post', models.TextField()),
                ('windowNumber', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=models.SET(julekalender.models.getDefaultDeletedUser), to=settings.AUTH_USER_MODEL)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='julekalender.Julekalender')),
            ],
        ),
        migrations.AddConstraint(
            model_name='window',
            constraint=models.UniqueConstraint(fields=('calendar', 'windowNumber'), name='uniqueWindow'),
        ),
    ]
