# Generated by Django 3.0.2 on 2021-08-31 08:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Julekalender',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False, verbose_name='år')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='tittel')),
                ('content', models.TextField(verbose_name='innhold')),
                ('submitted', models.DateTimeField(auto_now_add=True, verbose_name='lagt ut')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='redigert')),
                ('index', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='index')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='julekalender.Julekalender', verbose_name='kalender')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window_created', to=settings.AUTH_USER_MODEL, verbose_name='laga av')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window_modified', to=settings.AUTH_USER_MODEL, verbose_name='redigert av')),
            ],
        ),
        migrations.AddConstraint(
            model_name='window',
            constraint=models.UniqueConstraint(fields=('calendar', 'index'), name='uniqueWindow'),
        ),
    ]
