# Generated by Django 3.0.2 on 2020-02-21 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Julekalender',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('post', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Windows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windowNumber', models.IntegerField()),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='julekalender.Window')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='julekalender.Julekalender')),
            ],
        ),
        migrations.AddConstraint(
            model_name='windows',
            constraint=models.UniqueConstraint(fields=('year', 'windowNumber'), name='uniqueWindow'),
        ),
    ]
