# Generated by Django 3.2.9 on 2021-11-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julekalender', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='julekalender',
            options={'ordering': ['-year'], 'verbose_name': 'julekalender', 'verbose_name_plural': 'julekalendrar'},
        ),
        migrations.AlterModelOptions(
            name='window',
            options={'verbose_name': 'luke', 'verbose_name_plural': 'luker'},
        ),
        migrations.AlterField(
            model_name='window',
            name='content',
            field=models.TextField(verbose_name='innhald'),
        ),
    ]
