# Generated by Django 3.0.2 on 2020-08-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julekalender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='window',
            name='uniqueWindow',
        ),
        migrations.RenameField(
            model_name='window',
            old_name='windowNumber',
            new_name='index',
        ),
        migrations.AddConstraint(
            model_name='window',
            constraint=models.UniqueConstraint(fields=('calendar', 'index'), name='uniqueWindow'),
        ),
    ]
