# Generated by Django 3.2.9 on 2021-11-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julekalender', '0002_auto_20211124_0201'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='window',
            name='uniqueWindow',
        ),
        migrations.RenameField(
            model_name='window',
            old_name='calendar',
            new_name='advent_calendar',
        ),
        migrations.AddConstraint(
            model_name='window',
            constraint=models.UniqueConstraint(fields=('advent_calendar', 'index'), name='uniqueWindow'),
        ),
    ]
