# Generated by Django 3.0.2 on 2020-09-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('julekalender', '0002_auto_20200823_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='window',
            old_name='post',
            new_name='content',
        ),
    ]
