# Generated by Django 3.2.9 on 2021-11-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('julekalender', '0003_auto_20211129_1048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Julekalender',
            new_name='AdventCalendar',
        ),
    ]
