# Generated by Django 3.0.2 on 2020-11-25 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julekalender', '0003_auto_20200911_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='window',
            name='index',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
