# Generated by Django 3.0.2 on 2021-08-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julekalender', '0004_auto_20201125_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='julekalender',
            name='year',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='år'),
        ),
    ]
