# Generated by Django 3.0.2 on 2021-08-13 13:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import julekalender.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('julekalender', '0005_auto_20210813_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='window',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(julekalender.models.getDefaultDeletedUser), to=settings.AUTH_USER_MODEL, verbose_name='forfatter'),
        ),
        migrations.AlterField(
            model_name='window',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='julekalender.Julekalender', verbose_name='kalender'),
        ),
        migrations.AlterField(
            model_name='window',
            name='content',
            field=models.TextField(verbose_name='innhold'),
        ),
        migrations.AlterField(
            model_name='window',
            name='index',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='index'),
        ),
        migrations.AlterField(
            model_name='window',
            name='title',
            field=models.CharField(max_length=255, verbose_name='tittel'),
        ),
    ]
