# Generated by Django 4.1 on 2023-01-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Constant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="namn"),
                ),
                (
                    "value",
                    models.CharField(blank=True, max_length=255, verbose_name="verdi"),
                ),
            ],
            options={
                "verbose_name": "konstant",
                "verbose_name_plural": "konstantar",
                "ordering": ["name"],
            },
        ),
    ]
