# Generated by Django 4.0.2 on 2022-02-12 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='jakkenummer')),
                ('comment', models.TextField(blank=True, verbose_name='kommentar')),
                ('state', models.CharField(choices=[('GOOD', 'God'), ('OK', 'Ok'), ('BAD', 'Dårleg'), ('UNUSABLE', 'Ikkje brukbar')], default='OK', max_length=255, verbose_name='tilstand')),
            ],
            options={
                'verbose_name': 'jakke',
                'verbose_name_plural': 'jakker',
            },
        ),
        migrations.CreateModel(
            name='JacketLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='namn')),
            ],
            options={
                'verbose_name': 'jakkestad',
                'verbose_name_plural': 'jakkestadar',
            },
        ),
        migrations.CreateModel(
            name='JacketUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=True, verbose_name='er eigar')),
                ('jacket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jacket_users', to='uniforms.jacket', verbose_name='jakke')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jacket_user', to=settings.AUTH_USER_MODEL, verbose_name='brukar')),
            ],
            options={
                'verbose_name': 'Jakkebrukar',
                'verbose_name_plural': 'Jakkebrukarar',
                'ordering': ['user'],
            },
        ),
        migrations.AddField(
            model_name='jacket',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='jackets', to='uniforms.jacketlocation', verbose_name='stad'),
        ),
        migrations.AddConstraint(
            model_name='jacketuser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_owner', True)), fields=('jacket',), name='one_owner_per_jacket'),
        ),
    ]
