# Generated by Django 4.0 on 2021-12-18 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_alter_usercustom_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='JacketLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='namn')),
            ],
            options={
                'verbose_name': 'jakkestad',
                'verbose_name_plural': 'jakkestadar',
            },
        ),
        migrations.CreateModel(
            name='Jacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='jakkenummer')),
                ('comment', models.TextField(blank=True, verbose_name='kommentar')),
                ('state', models.CharField(choices=[('GOOD', 'God'), ('OK', 'Ok'), ('BAD', 'Dårleg'), ('UNUSABLE', 'Ikkje brukbar')], default='OK', max_length=255, verbose_name='tilstand')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='jackets', to='uniforms.jacketlocation', verbose_name='stad')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_jackets', to='accounts.usercustom', verbose_name='eigar')),
            ],
            options={
                'verbose_name': 'jakke',
                'verbose_name_plural': 'jakker',
            },
        ),
    ]
