# Generated by Django 4.0 on 2021-12-27 17:45

from django.db import migrations


def migrate_jacketusers(apps, schema_editor):
    User = apps.get_model("accounts", "UserCustom")
    JacketUser = apps.get_model("uniforms", "JacketUser")
    for user in User.objects.all():
        if user.jacket:
            JacketUser(
                jacket=user.jacket, user=user, is_owner=(user.jacket.owner == user)
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ("uniforms", "0002_jacketuser"),
    ]

    operations = [
        migrations.RunPython(migrate_jacketusers),
    ]
