# Generated by Django 4.0 on 2022-03-01 14:34

from django.db import migrations


def reset_jacket_state(apps, schema_editor):
    Jacket = apps.get_model("uniforms", "Jacket")
    for jacket in Jacket.objects.all():
        # Hardcode jacket state string since we don't want to depend on models.py
        jacket.state = "GOOD"
        jacket.save()


class Migration(migrations.Migration):

    dependencies = [
        ("uniforms", "0003_alter_jacket_state"),
    ]

    operations = [migrations.RunPython(reset_jacket_state)]
