# Generated by Django 4.0 on 2021-12-28 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_usercustom_jacket'),
        ('uniforms', '0004_remove_jacket_owner'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jacketuser',
            name='one_jacket_per_user',
        ),
        migrations.AlterField(
            model_name='jacketlocation',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='namn'),
        ),
        migrations.AlterField(
            model_name='jacketuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jacket_user', to='accounts.usercustom', verbose_name='brukar'),
        ),
    ]
