# Generated by Django 4.1 on 2022-10-09 10:57

from django.conf import settings
import django.utils.timezone
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("uniforms", "0004_auto_20220301_1534"),
    ]

    operations = [
        migrations.AddField(
            model_name="jacket",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="lagt ut"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jacket",
            name="created_by",
            field=django_userforeignkey.models.fields.UserForeignKey(
                blank=True,
                null=True,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="laga av",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jacket",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="redigert"),
        ),
        migrations.AddField(
            model_name="jacket",
            name="modified_by",
            field=django_userforeignkey.models.fields.UserForeignKey(
                blank=True,
                null=True,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="redigert av",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jacket",
            name="note",
            field=models.TextField(blank=True, verbose_name="merknad"),
        ),
        migrations.AddField(
            model_name="jacket",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uniforms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="vert lånt av",
            ),
        ),
    ]
