# Generated by Django 4.1 on 2022-10-09 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("uniforms", "0006_uniforms_modifiedmixin_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jacketuser",
            name="jacket",
        ),
        migrations.RemoveField(
            model_name="jacketuser",
            name="user",
        ),
        migrations.AlterField(
            model_name="jacket",
            name="created_by",
            field=django_userforeignkey.models.fields.UserForeignKey(
                blank=True,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="laga av",
            ),
        ),
        migrations.AlterField(
            model_name="jacket",
            name="modified_by",
            field=django_userforeignkey.models.fields.UserForeignKey(
                blank=True,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="redigert av",
            ),
        ),
        migrations.AddConstraint(
            model_name="jacket",
            constraint=models.UniqueConstraint(
                fields=("user",), name="one_owner_per_jacket"
            ),
        ),
        migrations.DeleteModel(
            name="JacketUser",
        ),
    ]
