# Generated by Django 4.1 on 2022-10-09 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("uniforms", "0007_alter_jacket_created_by_alter_jacket_modified_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jacket",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jackets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="eigar",
            ),
        ),
        migrations.DeleteModel(
            name="JacketUser",
        ),
    ]
