# Generated by Django 4.0.1 on 2022-01-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('storage_access', 'access to view storage access'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
