# Generated by Django 4.0.2 on 2022-02-10 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissioncustom',
            options={'default_permissions': (), 'managed': False, 'permissions': (('view_storage_access', 'Kan sjå lagertilgjenge'),)},
        ),
    ]
