image: docker/compose:1.29.2

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:stable-dind

stages:
  - test

test:
  stage: test
  script:
    - sh _setup/init.sh
    - docker-compose run web site/manage.py test site/
    - docker-compose run web flake8
    - docker-compose down
  only:
    - merge_requests
