image: docker/compose

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:stable-dind

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - sh setup/init.sh
    - docker-compose run django site/manage.py test site/
    - docker-compose run django flake8
    - docker-compose down
  only:
    - merge_requests
  tags:
    - docker

deploy:
  stage: deploy
  before_script:
    - apk update
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$ID_RSA" | tr -d '\r' | ssh-add - # funky stuffs from gitlab to remove line endings
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no "$SERVER_USER"@"$SERVER_IP" "~/veven/taktlausveven/deployment/deploy.sh"
    # Variables ID_RSA, SERVER_USER and SERVER_IP are set in settings -> ci/cd -> variables
  only:
    - master
