stages:
  - test
  - deploy

test:
  stage: test
  script:
    - export DATABASE_URL=postgres://taktlaus:$taktlaus@postgres:5432/taktlaus_db
    - apt update -qy
    - apt install python3 python3-pip virtualenvwrapper -qy
    - virtualenv --python=python3 venv/
    - source venv/bin/activate
    - pip install -r site/requirements.txt
    - cd site
    - python manage.py test 
  only:
    - develop

deploy:
  stage: deploy
  script:
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "~/deploy_scripts/deploy.sh"
  only:
    - master
