image: docker/compose

variables:
  GIT_SUBMODULE_STRATEGY: recursive

services:
  - docker:stable-dind

stages:
  - test
  - deploy
  - notification

verify-merge-request:
  stage: test
  before_script:
    - apk update
    - apk add openssh-client git
    - eval $(ssh-agent -s)
    - echo "$LINTBOT_SSH_PRIVATE_KEY" | base64 -d | ssh-add -
    - mkdir -p ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 700 ~/.ssh
    - git config --global user.email "lintbot@lint.police"
    - git config --global user.name "Overlintkonstabel Lintbot"
  script:
    - git fetch
    - git checkout $CI_COMMIT_REF_NAME
    - sh scripts/reset.sh
    - docker-compose run django site/manage.py test site/
    - docker-compose run django site/manage.py makemigrations --check --dry-run
    - docker-compose run django autoflake --in-place --remove-all-unused-imports -r site/
    - docker-compose run django isort .
    - docker-compose run django black .
    - docker-compose run django flake8
    - if [ "`git diff`" != "" ]; then git commit --all -m "Lint"; git push git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git; fi
    - docker-compose down
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

verify-deploy:
  stage: test
  script:
    - sh scripts/reset.sh
    - docker-compose run django site/manage.py test site/
    - docker-compose run django site/manage.py makemigrations --check --dry-run
    - docker-compose run django isort . -c
    - docker-compose run django black . --check
    - docker-compose run django flake8
    - docker-compose down
  rules:
    - if: $CI_COMMIT_TAG =~ /^v.*/

deploy:
  image: mcr.microsoft.com/azure-cli
  stage: deploy
  environment: production
  before_script:
    - az login --service-principal -u $AZURE_APP_ID -p $AZURE_PASSWORD --tenant $AZURE_TENANT
  script:
    - az acr build
      --resource-group taktlausveven
      --registry taktlausveven
      --image taktlausveven-django:latest
      --file deployment/Dockerfile.prod .
    - curl $PULL_IMAGE_WEBHOOK -d ""
    - sleep 300
    - curl https://taktlaus.no/
      --fail
      --max-time 20
      --retry 3
  rules:
    - if: $CI_COMMIT_TAG =~ /^v.*/

success-notification:
  stage: notification
  image: alpine:latest
  script:
    - apk add --update git curl
    - wget https://raw.githubusercontent.com/Shybert/gitlab-ci-discord-webhook/proper-logos/send.sh
    - chmod +x send.sh
    - sh send.sh success $DISCORD_DEPLOY_NOTIFICATION_WEBHOOK
  rules:
    - if: $CI_COMMIT_TAG =~ /^v.*/
  when: on_success
failure-notification:
  stage: notification
  image: alpine:latest
  script:
    - apk add --update git curl
    - wget https://raw.githubusercontent.com/Shybert/gitlab-ci-discord-webhook/proper-logos/send.sh
    - chmod +x send.sh
    - sh send.sh failure $DISCORD_DEPLOY_NOTIFICATION_WEBHOOK
  rules:
    - if: $CI_COMMIT_TAG =~ /^v.*/
  when: on_failure
