version: "3"

services:
  db:
    image: postgres
    volumes:
      - ~/taktlausveven_db:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_DB=taktlaus_db
      - POSTGRES_USER=taktlaus
      - POSTGRES_PASSWORD=taktlaus

  web:
    build: .
    environment:
      - DEBUG=1
    volumes:
      - ./site:/app/site:Z
    command: ./site/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
