version: "3"

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - ~/.taktlaus_db:/var/lib/postgresql/data:Z
    env_file:
      - ./.env.prod.db

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - static_files:/app/staticfiles
      - media_files:/app/media
    env_file:
      - ./.env.prod
    command: gunicorn web.wsgi:application --bind 0.0.0.0:8000 --chdir site
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    build: ./deployment/nginx
    volumes:
      - static_files:/app/staticfiles
      - media_files:/app/media
    ports:
      - 8000:80
    depends_on:
      - web

volumes:
  static_files:
  media_files: