version: "3"

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - db_dev:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_DB=taktlaus_db
      - POSTGRES_USER=taktlaus
      - POSTGRES_PASSWORD=taktlaus

  django:
    build: .
    volumes:
      - ./site:/app/site:Z
      - ./.flake8:/app/.flake8:Z
      - ./pyproject.toml:/app/pyproject.toml:Z
      - ./setup/wait-for-it.sh:/app/wait-for-it.sh:Z
    command: sh -c './wait-for-it.sh db:5432 -- ./site/manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  db_dev: