# Generated by Django 3.2.7 on 2021-09-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='namn')),
                ('email', models.EmailField(max_length=254, verbose_name='e-post')),
            ],
            options={
                'verbose_name': 'kontaktkategori',
                'verbose_name_plural': 'kontaktkategoriar',
            },
        ),
    ]
