# Generated by Django 4.0 on 2021-12-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'kontaktkategori', 'verbose_name_plural': 'kontaktkategoriar'},
        ),
        migrations.AddField(
            model_name='contactcategory',
            name='order',
            field=models.IntegerField(default=0, help_text='Definerer rekkjefølgja til kategoriar. Kategoriar med lik ordning blir sortert etter namn.', verbose_name='ordning'),
        ),
    ]
