# Generated by Django 4.0 on 2022-01-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactcategory_options_contactcategory_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcategory',
            name='order',
            field=models.IntegerField(default=0, help_text='Definerer rekkjefølgja til kategoriar. Kategoriar med lik rekkjefølgje blir sortert etter namn.', verbose_name='rekkjefølgje'),
        ),
    ]
