# Generated by Django 4.0.1 on 2022-01-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advent_calendar', '0002_alter_window_content_alter_window_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='window',
            old_name='submitted',
            new_name='created',
        ),
    ]
