# Generated by Django 3.0.2 on 2021-07-26 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20210725_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='lagt ut'),
            preserve_default=False,
        ),
    ]
