# Generated by Django 3.2.10 on 2021-12-11 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='dato'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='til dato'),
        ),
    ]
