# Generated by Django 4.0.1 on 2022-01-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order', 'uploaded'], 'verbose_name': 'bilete', 'verbose_name_plural': 'bilete'},
        ),
    ]
