# Generated by Django 3.2.10 on 2021-12-11 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20211211_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='bilde')),
                ('description', models.CharField(blank=True, max_length=1024, verbose_name='beskrivelse')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pictures.gallery', verbose_name='galleri')),
            ],
            options={
                'verbose_name': 'bilete',
                'verbose_name_plural': 'bilete',
            },
        ),
    ]
