# Generated by Django 4.1 on 2022-10-08 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_alter_eventcategory_options"),
        ("pictures", "0003_alter_gallery_created_by_alter_gallery_modified_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="connected_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="connected_event",
                to="events.event",
                verbose_name="Oppkobla hending",
            ),
        ),
    ]
