# Generated by Django 4.0.1 on 2022-01-22 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_alter_gallery_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['images__uploaded', 'modified'], 'verbose_name': 'galleri', 'verbose_name_plural': 'galleri'},
        ),
    ]
