# Generated by Django 4.0 on 2021-12-22 18:18

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='tittel')),
                ('description', models.CharField(max_length=255, verbose_name='innhald')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique=True, verbose_name='lenkjenamn')),
            ],
            options={
                'verbose_name': 'forum',
                'verbose_name_plural': 'forum',
                'ordering': ['title'],
            },
        ),
    ]
