# Generated by Django 4.0.1 on 2022-01-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'created', 'ordering': ['created'], 'verbose_name': 'innlegg', 'verbose_name_plural': 'innlegg'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='submitted',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='submitted',
            new_name='created',
        ),
    ]
