# Generated by Django 4.0 on 2021-12-22 18:44

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usercustom_jacket'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='tittel')),
                ('content', models.TextField(verbose_name='innhald')),
                ('submitted', models.DateTimeField(auto_now_add=True, verbose_name='lagt ut')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='redigert')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique=True, verbose_name='lenkjenamn')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to='accounts.usercustom', verbose_name='laga av')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='forum.forum', verbose_name='forum')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified', to='accounts.usercustom', verbose_name='redigert av')),
            ],
            options={
                'verbose_name': 'emne',
                'verbose_name_plural': 'emne',
            },
        ),
    ]
