# Generated by Django 4.0 on 2021-12-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-submitted'], 'verbose_name': 'innlegg', 'verbose_name_plural': 'innlegg'},
        ),
    ]
