# Generated by Django 4.0 on 2021-12-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-posts__submitted'], 'verbose_name': 'emne', 'verbose_name_plural': 'emne'},
        ),
    ]
