# Generated by Django 4.0 on 2021-12-22 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_topic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'emne', 'verbose_name_plural': 'emne'},
        ),
    ]
