# Generated by Django 4.0 on 2021-12-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_topic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-submitted'], 'verbose_name': 'emne', 'verbose_name_plural': 'emne'},
        ),
    ]
