# Generated by Django 4.0 on 2021-12-23 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_topic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'submitted', 'ordering': ['-submitted'], 'verbose_name': 'innlegg', 'verbose_name_plural': 'innlegg'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'emne', 'verbose_name_plural': 'emne'},
        ),
    ]
