# Generated by Django 4.0 on 2021-12-23 14:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique_with=('forum',), verbose_name='lenkjenamn'),
        ),
    ]
