# Generated by Django 4.0 on 2021-12-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_alter_topic_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'submitted', 'ordering': ['submitted'], 'verbose_name': 'innlegg', 'verbose_name_plural': 'innlegg'},
        ),
    ]
