# Generated by Django 4.0 on 2021-12-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_alter_topic_options_remove_topic_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'get_latest_by': 'posts__submitted', 'ordering': ['-posts__submitted'], 'verbose_name': 'emne', 'verbose_name_plural': 'emne'},
        ),
    ]
