# Generated by Django 4.0 on 2021-12-24 12:59

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_alter_topic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'get_latest_by': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('posts__submitted'), nulls_last=True)], 'ordering': ['-posts__submitted'], 'verbose_name': 'emne', 'verbose_name_plural': 'emne'},
        ),
    ]
