# Generated by Django 4.0 on 2021-12-24 13:08

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_alter_topic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'get_latest_by': [django.db.models.expressions.Case(django.db.models.expressions.When(posts__submitted=None, then=django.db.models.expressions.F('submitted')), default=django.db.models.expressions.F('posts__submitted'))], 'ordering': ['-posts__submitted'], 'verbose_name': 'emne', 'verbose_name_plural': 'emne'},
        ),
    ]
