# Generated by Django 4.0 on 2021-12-24 13:23

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_alter_topic_options_topic_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'get_latest_by': [django.db.models.expressions.Case(django.db.models.expressions.When(posts__submitted=None, then='submitted'), default='posts__submitted')], 'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.Case(django.db.models.expressions.When(posts__submitted=None, then='submitted'), default='posts__submitted'))], 'verbose_name': 'emne', 'verbose_name_plural': 'emne'},
        ),
    ]
