# Generated by Django 4.0 on 2021-12-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_alter_topic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'get_latest_by': ['posts__submitted'], 'ordering': ['-posts__submitted'], 'verbose_name': 'emne', 'verbose_name_plural': 'emne'},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='content',
        ),
    ]
