# Generated by Django 4.0 on 2021-12-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_alter_topic_options_remove_topic_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'emne', 'verbose_name_plural': 'emne'},
        ),
        migrations.AddField(
            model_name='topic',
            name='content',
            field=models.TextField(default='', verbose_name='innhald'),
            preserve_default=False,
        ),
    ]
