# Generated by Django 4.0 on 2021-12-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0024_alter_topic_options_topic_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='content',
        ),
    ]
