# Generated by Django 4.0.3 on 2022-07-20 11:40

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='lagt ut')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='redigert')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='namn')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True, verbose_name='lenkjenamn')),
                ('image', models.ImageField(upload_to='pictures/', verbose_name='bilete')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='laga av')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='redigert av')),
            ],
            options={
                'verbose_name': 'buttonmotiv',
                'verbose_name_plural': 'buttonmotiv',
                'ordering': ['name'],
            },
        ),
    ]
