# Generated by Django 3.2.9 on 2021-12-07 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='namn')),
            ],
            options={
                'verbose_name': 'instrumentgruppe',
                'verbose_name_plural': 'instrumentgrupper',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='namn')),
                ('location', models.CharField(max_length=255, verbose_name='stad')),
                ('serial_number', models.CharField(max_length=255, verbose_name='serienummer')),
                ('comment', models.TextField(verbose_name='kommentar')),
                ('state', models.CharField(choices=[('GOOD', 'god'), ('OK', 'ok'), ('BAD', 'dårleg'), ('UNPLAYABLE', 'ikkje spelbart')], default='OK', max_length=255)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instruments', to='instruments.instrumenttype', verbose_name='instrumentgruppe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instruments', to=settings.AUTH_USER_MODEL, verbose_name='vert lånt av')),
            ],
        ),
    ]
