# Generated by Django 4.0.2 on 2022-02-12 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstrumentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="namn"),
                ),
            ],
            options={
                "verbose_name": "instrumentgruppe",
                "verbose_name_plural": "instrumentgrupper",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InstrumentLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="namn"),
                ),
            ],
            options={
                "verbose_name": "instrumentstad",
                "verbose_name_plural": "instrumentstadar",
            },
        ),
        migrations.CreateModel(
            name="InstrumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="namn"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types",
                        to="instruments.instrumentgroup",
                        verbose_name="instrumentgruppe",
                    ),
                ),
            ],
            options={
                "verbose_name": "instrumenttype",
                "verbose_name_plural": "instrumenttyper",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="namn"),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="serienummer"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="kommentar")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("GOOD", "God"),
                            ("OK", "Ok"),
                            ("BAD", "Dårleg"),
                            ("UNPLAYABLE", "Ikkje spelbart"),
                        ],
                        default="OK",
                        max_length=255,
                        verbose_name="tilstand",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="instruments",
                        to="instruments.instrumentgroup",
                        verbose_name="instrumentgruppe",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="instruments",
                        to="instruments.instrumentlocation",
                        verbose_name="stad",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instruments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="vert lånt av",
                    ),
                ),
            ],
            options={
                "verbose_name": "instrument",
                "verbose_name_plural": "instrument",
            },
        ),
    ]
