# Generated by Django 3.2.9 on 2021-12-07 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='namn')),
            ],
            options={
                'verbose_name': 'instrumentgruppe',
                'verbose_name_plural': 'instrumentgrupper',
            },
        ),
        migrations.CreateModel(
            name='InstrumentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='namn')),
            ],
            options={
                'verbose_name': 'instrumentstad',
                'verbose_name_plural': 'instrumentstadar',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='namn')),
                ('serial_number', models.CharField(blank=True, max_length=255, verbose_name='serienummer')),
                ('comment', models.TextField(blank=True, verbose_name='kommentar')),
                ('state', models.IntegerField(choices=[(0, 'God'), (1, 'Ok'), (2, 'Dårleg'), (3, 'Ikkje spelbart')], default=1, verbose_name='tilstand')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instruments', to='instruments.instrumentgroup', verbose_name='instrumentgruppe')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instruments', to='instruments.instrumentlocation', verbose_name='stad')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instruments', to=settings.AUTH_USER_MODEL, verbose_name='vert lånt av')),
            ],
            options={
                'verbose_name': 'instrument',
                'verbose_name_plural': 'instrument',
            },
        ),
    ]
