# Generated by Django 4.0.2 on 2022-02-22 08:46

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['type', 'identifier'], 'verbose_name': 'instrument', 'verbose_name_plural': 'instrument'},
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='group',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='name',
        ),
        migrations.AddField(
            model_name='instrument',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, verbose_name='identifikator'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='instruments', to='instruments.instrumenttype', verbose_name='instrumenttype'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('type'), django.db.models.expressions.F('identifier'), name='unique_instrument'),
        ),
    ]
