# Generated by Django 3.2.9 on 2021-12-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'verbose_name': 'instrument', 'verbose_name_plural': 'instrument'},
        ),
        migrations.AlterField(
            model_name='instrument',
            name='comment',
            field=models.TextField(blank=True, verbose_name='kommentar'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='serienummer'),
        ),
    ]
