# Generated by Django 4.0.1 on 2022-01-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentgroup',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='namn'),
        ),
        migrations.AlterField(
            model_name='instrumentlocation',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='namn'),
        ),
    ]
