# Generated by Django 3.2.9 on 2021-12-07 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_auto_20211207_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='state',
            field=models.CharField(choices=[('GOOD', 'God'), ('OK', 'Ok'), ('BAD', 'Dårleg'), ('UNPLAYABLE', 'Ikkje spelbart')], default='OK', max_length=255, verbose_name='tilstand'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instruments', to='instruments.instrumenttype', verbose_name='instrumentgruppe'),
            preserve_default=False,
        ),
    ]
