# Generated by Django 4.0.1 on 2022-01-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_instrumenttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentgroup',
            options={'ordering': ['name'], 'verbose_name': 'instrumentgruppe', 'verbose_name_plural': 'instrumentgrupper'},
        ),
        migrations.AlterModelOptions(
            name='instrumenttype',
            options={'ordering': ['name'], 'verbose_name': 'instrumenttype', 'verbose_name_plural': 'instrumenttyper'},
        ),
    ]
