# Generated by Django 4.1 on 2022-10-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0003_remove_instrument_unique_instrument_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="last_modified",
            field=models.DateTimeField(auto_now=True, verbose_name="Sist endra"),
        ),
    ]
