# Generated by Django 3.2.9 on 2021-12-07 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_instrument_type_usercustom_instrument_group'),
        ('instruments', '0003_auto_20211207_2132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstrumentType',
            new_name='InstrumentGroup',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='type',
            new_name='group',
        ),
    ]
