# Generated by Django 4.1 on 2022-10-07 13:56

from django.conf import settings
from django.db import migrations


def find_test_user(user_model):
    if settings.DEBUG:
        return user_model.objects.get_or_create(username="test", name="Trine Taktlaus")[
            0
        ]
    else:
        return user_model.objects.get(username="test")


def set_instrument_created_by_modified_by(apps, schema_editor):
    UserCustom = apps.get_model("accounts", "UserCustom")
    Instruments = apps.get_model("instruments", "Instrument")
    for instrument in Instruments.objects.all():
        test_user = find_test_user(UserCustom)
        instrument.created_by = test_user
        instrument.modified_by = test_user
        instrument.save()


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0004_instrument_created_instrument_created_by_and_more"),
    ]

    operations = [
        migrations.RunPython(set_instrument_created_by_modified_by),
    ]
