# Generated by Django 4.1 on 2022-12-09 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0006_alter_instrument_created_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstrumentTypeDetectionKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="nykelord"
                    ),
                ),
                (
                    "instrument_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_keywords",
                        to="instruments.instrumenttype",
                        verbose_name="instrumenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "instrumenttypeattkjenningsnykelord",
                "verbose_name_plural": "instrumenttypeattkjenningsnykelord",
                "ordering": ["keyword"],
            },
        ),
        migrations.CreateModel(
            name="InstrumentTypeDetectionException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exception", models.CharField(max_length=255, verbose_name="unntak")),
                (
                    "instrument_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_exceptions",
                        to="instruments.instrumenttype",
                        verbose_name="instrumenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "instrumenttypeattkjenningsunntak",
                "verbose_name_plural": "instrumenttypeattkjenningsunntak",
                "ordering": ["exception"],
            },
        ),
        migrations.AddConstraint(
            model_name="instrumenttypedetectionexception",
            constraint=models.UniqueConstraint(
                fields=("exception", "instrument_type"),
                name="detection_exception_unique_for_instrument_type",
            ),
        ),
    ]
