# syntax=docker/dockerfile:1
FROM python:3.10.0
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=web.settings
WORKDIR /app

COPY scripts/sheetmusic.sh /app/
ARG SHEETMUSIC="yes"
RUN if [ $SHEETMUSIC = yes ]; then sh sheetmusic.sh; fi

COPY site/requirements.txt site/requirements.prod.txt /app/
RUN pip install --no-cache -r requirements.txt -r requirements.prod.txt

COPY ./site /app/site/
