# Generated by Django 3.0.2 on 2020-01-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='owner',
            field=models.CharField(default='Anonym', max_length=255),
            preserve_default=False,
        ),
    ]
