# Generated by Django 4.1 on 2022-08-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0002_rename_owner_quote_context_rename_text_quote_quote_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="quoted_as",
            field=models.CharField(max_length=255, verbose_name="sitert som"),
        ),
        migrations.AlterField(
            model_name="quote",
            name="quote",
            field=models.TextField(verbose_name="sitat"),
        ),
    ]
