# Generated by Django 4.1 on 2022-08-21 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quotes", "0003_alter_quote_context_alter_quote_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="users",
            field=models.ManyToManyField(
                related_name="quotes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="den/dei som vert sitert",
            ),
        ),
    ]
