# Generated by Django 3.2.7 on 2021-09-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20200219_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-timestamp'], 'verbose_name': 'sitat', 'verbose_name_plural': 'sitat'},
        ),
    ]
