# Generated by Django 4.1 on 2022-08-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0005_alter_quote_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="quoted_as",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="sitert som"
            ),
        ),
    ]
