# Generated by Django 4.1 on 2022-11-10 22:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quotes", "0005_alter_quote_created_by_alter_quote_modified_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="quotes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="involverte medlemmar",
            ),
        ),
    ]
