# Generated by Django 3.2.9 on 2021-11-29 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sheetmusic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repertoire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RepertoireEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repertoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='repertoire.repertoire')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repertoireEntries', to='sheetmusic.score')),
            ],
        ),
    ]
