# Generated by Django 3.2.9 on 2021-11-30 09:13

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sheetmusic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repertoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='namn')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='tidsmerke')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True, verbose_name='lenkjenamn')),
            ],
            options={
                'verbose_name': 'repertoar',
                'verbose_name_plural': 'repertoar',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RepertoireEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repertoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='repertoire.repertoire', verbose_name='repertoar')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repertoire_entries', to='sheetmusic.score', verbose_name='note')),
            ],
            options={
                'verbose_name': 'repertoaroppføring',
                'verbose_name_plural': 'repertoaroppføringar',
            },
        ),
        migrations.AddConstraint(
            model_name='repertoire',
            constraint=models.UniqueConstraint(fields=('slug',), name='repertoire_unique_slug'),
        ),
        migrations.AddConstraint(
            model_name='repertoireentry',
            constraint=models.UniqueConstraint(fields=('repertoire', 'score'), name='repertoire_unique_entry'),
        ),
    ]
