# Generated by Django 4.0.3 on 2022-05-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repertoireentry',
            options={'ordering': ['score'], 'verbose_name': 'repertoaroppføring', 'verbose_name_plural': 'repertoaroppføringar'},
        ),
    ]
