# Generated by Django 4.0.2 on 2022-02-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repertoire',
            options={'ordering': ['order', 'name'], 'verbose_name': 'repertoar', 'verbose_name_plural': 'repertoar'},
        ),
        migrations.AddField(
            model_name='repertoire',
            name='order',
            field=models.FloatField(default=0, help_text='Definerer rekkjefølgja til repertoaret. Repertoar med lik rekkjefølgje vert sortert etter namn.', verbose_name='rekkjefølgje'),
        ),
    ]
