# Generated by Django 3.2.8 on 2021-10-13 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0009_remove_userspreferredpart_score'),
        ('repertoire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepertoireEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repertoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='repertoire.repertoire')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repertoireEntries', to='sheetmusic.score')),
            ],
        ),
    ]
