# Generated by Django 4.1 on 2022-08-23 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("repertoire", "0002_alter_repertoireentry_options"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="repertoire",
            name="repertoire_unique_slug",
        ),
        migrations.AddField(
            model_name="repertoire",
            name="active_until",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Valfritt. Gjer repertoaret aktivt til og med ein bestemt dato. Om inga dato er satt vert det aktivt for alltid.",
                null=True,
                verbose_name="aktivt til",
            ),
        ),
        migrations.AddField(
            model_name="repertoire",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="lagt ut",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="repertoire",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="laga av",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="repertoire",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="redigert"),
        ),
        migrations.AddField(
            model_name="repertoire",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="redigert av",
            ),
            preserve_default=False,
        ),
    ]
