# Generated by Django 4.1 on 2022-08-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repertoire", "0002_alter_repertoireentry_options"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="repertoire",
            name="repertoire_unique_slug",
        ),
        migrations.AddField(
            model_name="repertoire",
            name="active_until",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Valfritt. Gjer repertoaret aktivt til og med ein bestemt dato. Om inga dato er satt vert det aktivt for alltid.",
                null=True,
                verbose_name="aktivt til",
            ),
        ),
    ]
