# Generated by Django 4.1 on 2022-08-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repertoire", "0002_alter_repertoireentry_options"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="repertoire",
            name="repertoire_unique_slug",
        ),
        migrations.AddField(
            model_name="repertoire",
            name="active_until",
            field=models.DateField(
                blank=True,
                default=None,
                help_text='Gjer repertoaret aktivt til og med ein bestemt dato. Kan ikkje nyttast saman med "Alltid aktivt".',
                null=True,
                verbose_name="aktivt til",
            ),
        ),
        migrations.AddField(
            model_name="repertoire",
            name="always_active",
            field=models.BooleanField(default=True, verbose_name="alltid aktivt"),
        ),
        migrations.AddConstraint(
            model_name="repertoire",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("always_active", False),
                    ("active_until__isnull", True),
                    _connector="OR",
                ),
                name="repertoire_not_always_active_and_active_until",
                violation_error_message='Eit repertoar kan ikkje vere både "Alltid aktivt" og "Aktivt til"',
            ),
        ),
    ]
