# Generated by Django 4.1 on 2022-08-24 09:38

from django.conf import settings
from django.db import migrations


def find_test_user(user_model):
    if settings.DEBUG:
        return user_model.objects.get_or_create(username="test", name="Trine Taktlaus")[0]
    else:
        return user_model.objects.get(username="test")
    

def set_repertoire_created_by_modified_by(apps, schema_editor):
    UserCustom = apps.get_model("accounts", "UserCustom")
    Repertoire = apps.get_model("repertoire", "Repertoire")
    test_user = find_test_user(UserCustom)
    for repertoire in Repertoire.objects.all():
        repertoire.created_by = test_user
        repertoire.modified_by = test_user
        repertoire.created = repertoire.timestamp
        repertoire.save()


class Migration(migrations.Migration):

    dependencies = [
        ("repertoire", "0003_repertoire_history"),
    ]

    operations = [
        migrations.RunPython(set_repertoire_created_by_modified_by),
    ]
