# Generated by Django 4.1 on 2022-10-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheetmusic", "0006_score_transcribed_by"),
        ("repertoire", "0007_alter_repertoire_created_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="repertoireentry",
            options={
                "ordering": ["order", "score"],
                "verbose_name": "repertoaroppføring",
                "verbose_name_plural": "repertoaroppføringar",
            },
        ),
        migrations.AddField(
            model_name="repertoire",
            name="scores",
            field=models.ManyToManyField(
                blank=True,
                through="repertoire.RepertoireEntry",
                to="sheetmusic.score",
                verbose_name="notar",
            ),
        ),
        migrations.AddField(
            model_name="repertoireentry",
            name="order",
            field=models.FloatField(
                default=0,
                help_text="Definerer rekkjefølgja til nota i repertoaret.Notar med lik rekkjefølgje vert sortert alfabetisk.",
                verbose_name="rekkjefølgje",
            ),
        ),
    ]
