# Generated by Django 4.1 on 2022-10-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheetmusic", "0006_score_transcribed_by"),
        ("repertoire", "0007_alter_repertoire_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repertoire",
            name="scores",
            field=models.ManyToManyField(
                related_name="repertoires", to="sheetmusic.score", verbose_name="notar"
            ),
        ),
    ]
