# Generated by Django 4.1 on 2023-05-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repertoire", "0010_delete_repertoireentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repertoire",
            name="active_until",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Valfritt. Gjer repertoaret aktivt til og med ein bestemt dato. Om inga dato er satt vert det aktivt for alltid.",
                null=True,
                verbose_name="aktivt til og med",
            ),
        ),
    ]
