# Generated by Django 3.2.9 on 2021-11-27 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import upload_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='namn')),
                ('from_page', models.IntegerField(default=None, verbose_name='første side')),
                ('to_page', models.IntegerField(default=None, verbose_name='siste side')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='tidsmerke')),
            ],
            options={
                'verbose_name': 'stemme',
                'verbose_name_plural': 'stemmer',
                'ordering': ['pdf', 'from_page', 'to_page', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='tittel')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='tidsmerke')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notar',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UsersPreferredPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferring_users', to='sheetmusic.part', verbose_name='stemme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_parts', to=settings.AUTH_USER_MODEL, verbose_name='brukar')),
            ],
            options={
                'verbose_name': 'brukarfavorittstemme',
                'verbose_name_plural': 'brukarfavorittstemmer',
                'ordering': ['user', 'part'],
            },
        ),
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, upload_to='sheetmusic/original_pdfs/', validators=[upload_validator.FileTypeValidator(allowed_extensions=['.pdf', '.PDF'], allowed_types=['application/pdf', 'application/x-pdf', 'application/x-bzpdf', 'application/x-gzpdf'])], verbose_name='fil')),
                ('processing', models.BooleanField(default=False, editable=False, verbose_name='prosessering pågår')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='tidsmerke')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='sheetmusic.score', verbose_name='note')),
            ],
            options={
                'verbose_name': 'pdf',
                'verbose_name_plural': 'pdfar',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='part',
            name='pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='sheetmusic.pdf', verbose_name='pdf'),
        ),
    ]
