# Generated by Django 4.0.2 on 2022-02-21 20:49

import autoslug.fields
from django.db import migrations
import sheetmusic.models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from=sheetmusic.models.Part.__str__, unique_with=('pdf__score__slug',), verbose_name='lenkjenamn'),
        ),
    ]
