# Generated by Django 3.2.10 on 2021-12-13 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sheetmusic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['title', '-submitted'], 'verbose_name': 'note', 'verbose_name_plural': 'notar'},
        ),
        migrations.RemoveField(
            model_name='score',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='score',
            name='arrangement',
            field=models.CharField(blank=True, max_length=255, verbose_name='arrangement'),
        ),
        migrations.AddField(
            model_name='score',
            name='content',
            field=models.TextField(blank=True, verbose_name='beskriving'),
        ),
        migrations.AddField(
            model_name='score',
            name='created_by',
            field=models.ForeignKey(default=None, blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_created', to='accounts.usercustom', verbose_name='laga av'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='redigert'),
        ),
        migrations.AddField(
            model_name='score',
            name='modified_by',
            field=models.ForeignKey(default=None, blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_modified', to='accounts.usercustom', verbose_name='redigert av'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='originally_from',
            field=models.CharField(blank=True, max_length=255, verbose_name='opphaveleg ifrå'),
        ),
        migrations.AddField(
            model_name='score',
            name='sound_file',
            field=models.FileField(blank=True, default="", upload_to='sheetmusic/sound_files/', validators=[], verbose_name='lydfil'),
        ),
        migrations.AddField(
            model_name='score',
            name='sound_link',
            field=models.URLField(blank=True, verbose_name='lydlenkje'),
        ),
        migrations.AddField(
            model_name='score',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='lagt ut'),
            preserve_default=False,
        ),
    ]
