# Generated by Django 3.2.10 on 2021-12-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='arrangement',
            field=models.CharField(blank=True, max_length=255, verbose_name='arrangement'),
        ),
        migrations.AddField(
            model_name='score',
            name='description',
            field=models.TextField(blank=True, verbose_name='beskriving'),
        ),
        migrations.AddField(
            model_name='score',
            name='originally_from',
            field=models.CharField(blank=True, max_length=255, verbose_name='originalt ifrå'),
        ),
        migrations.AddField(
            model_name='score',
            name='sound_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='sheetmusic/sound_files/', verbose_name='lydfil'),
        ),
        migrations.AddField(
            model_name='score',
            name='sound_link',
            field=models.URLField(blank=True, verbose_name='lydlenkje'),
        ),
    ]
