# Generated by Django 3.0.2 on 2020-11-14 21:42

from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0002_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='file',
            field=models.FileField(default=None, upload_to='sheetmusic/original_pdfs/', validators=[upload_validator.FileTypeValidator(allowed_extensions=['.pdf', '.PDF'], allowed_types=['application/pdf', 'application/x-pdf', 'application/x-bzpdf', 'application/x-gzpdf'])]),
        ),
    ]
