# Generated by Django 4.1 on 2022-08-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheetmusic", "0002_alter_part_slug"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="part",
            name="unique_part",
        ),
        migrations.AddConstraint(
            model_name="part",
            constraint=models.UniqueConstraint(
                fields=("pdf", "instrument_type", "part_number", "note"),
                name="unique_part",
            ),
        ),
    ]
