# Generated by Django 3.2.10 on 2021-12-13 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

def add_random_user(apps, schema_editor):
    User = apps.get_model("accounts", "UserCustom")
    user = User.objects.last()
    if user is None:
        user = User(username="randomnotesjef")
    Score = apps.get_model("sheetmusic", "Score")
    for score in Score.objects.all():
        if score.created_by is None:
            score.created_by = user
        if score.modified_by is None:
            score.modified_by = user


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sheetmusic', '0002_auto_20211213_2344'),
    ]

    operations = [
        migrations.RunPython(add_random_user),
    ]
