# Generated by Django 3.2.10 on 2021-12-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0002_auto_20211213_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='sound_file',
            field=models.FileField(blank=True, default=None, upload_to='sheetmusic/sound_files/', verbose_name='lydfil'),
        ),
    ]
