# Generated by Django 3.2.10 on 2021-12-13 21:29

from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0003_alter_score_sound_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='sound_file',
            field=models.FileField(blank=True, default=None, upload_to='sheetmusic/sound_files/', validators=[upload_validator.FileTypeValidator(allowed_extensions=['.mp3', '.midi', '.mid', '.ogg', '.mp4', '.m4a', '.flac'], allowed_types=['audio/mp3', 'audio/midi', 'audio/ogg', 'audio/mp4', 'audio/flac'])], verbose_name='lydfil'),
        ),
    ]
