# Generated by Django 3.0.2 on 2020-11-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0003_auto_20201114_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='fromPage',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='part',
            name='toPage',
            field=models.IntegerField(default=None),
        ),
    ]
