# Generated by Django 3.2.10 on 2021-12-13 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sheetmusic', '0003_add_random_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_created', to='accounts.usercustom', verbose_name='laga av'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_modified', to='accounts.usercustom', verbose_name='redigert av'),
            preserve_default=False,
        ),
    ]
