# Generated by Django 3.0.2 on 2021-01-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0004_auto_20201115_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='processing',
            field=models.BooleanField(default=False),
        ),
    ]
