# Generated by Django 4.1 on 2022-10-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheetmusic", "0005_alter_score_created_by_alter_score_modified_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="transcribed_by",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="transkribert av"
            ),
        ),
    ]
