# Generated by Django 3.0.2 on 2021-05-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0005_pdf_processing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
