# Generated by Django 4.0 on 2021-12-22 10:51

import common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usercustom_jacket'),
        ('sheetmusic', '0005_auto_20211216_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to='accounts.usercustom', verbose_name='laga av'),
        ),
        migrations.AlterField(
            model_name='score',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified', to='accounts.usercustom', verbose_name='redigert av'),
        ),
        migrations.AlterField(
            model_name='score',
            name='sound_file',
            field=models.FileField(blank=True, default='', upload_to='sheetmusic/sound_files/', validators=[common.validators.FileTypeValidator({'audio/flac': ['.flac'], 'audio/midi': ['.midi', '.mid'], 'audio/mp4': ['.mp4', '.m4a'], 'audio/mpeg': ['.mp3'], 'audio/ogg': ['.ogg']})], verbose_name='lydfil'),
        ),
    ]
