# Generated by Django 4.1 on 2022-11-18 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sheetmusic", "0006_score_transcribed_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Original",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to="sheetmusic/original_files/",
                        verbose_name="fil",
                    ),
                ),
                (
                    "filename_original",
                    models.CharField(max_length=255, verbose_name="opphaveleg filnamn"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="tidsmerke"),
                ),
                (
                    "score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="originals",
                        to="sheetmusic.score",
                        verbose_name="note",
                    ),
                ),
            ],
            options={
                "verbose_name": "original",
                "verbose_name_plural": "originalar",
                "ordering": ["filename_original"],
            },
        ),
    ]
