# Generated by Django 4.0 on 2021-12-23 13:26

import autoslug.fields
from django.db import migrations
from ..models import pdf_slug_populate_from


def populate_pdf_slugs(apps, schema_editor):
    Pdf = apps.get_model("sheetmusic", "Pdf")
    for pdf in Pdf.objects.all():
        if pdf.slug == "nothing":
            # Setting slug to None and calling save will make autoslug generate a new and unique slug
            pdf.slug = None
            pdf.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0006_alter_score_created_by_alter_score_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='nothing', editable=True, populate_from=pdf_slug_populate_from, unique_with=('score__slug',), verbose_name='lenkjenamn'),
            preserve_default=False,
        ),
        migrations.RunPython(populate_pdf_slugs),
    ]
