# Generated by Django 4.1 on 2022-11-20 23:51

import common.forms.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sheetmusic", "0006_score_transcribed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdf",
            name="file",
            field=models.FileField(
                default=None,
                max_length=255,
                upload_to="sheetmusic/original_pdfs/",
                validators=[common.forms.validators.FileTypeValidator([".pdf"])],
                verbose_name="fil",
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="sound_file",
            field=models.FileField(
                blank=True,
                default="",
                upload_to="sheetmusic/sound_files/",
                validators=[
                    common.forms.validators.FileTypeValidator(
                        [".mp3", ".midi", ".mid", ".ogg", ".mp4", ".m4a", ".flac"]
                    )
                ],
                verbose_name="lydfil",
            ),
        ),
        migrations.CreateModel(
            name="EditFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to="sheetmusic/edit_files/",
                        validators=[
                            common.forms.validators.FileTypeValidator(
                                [".mscz", ".mscx", ".niff", ".sib", ".musx"]
                            )
                        ],
                        verbose_name="fil",
                    ),
                ),
                (
                    "filename_original",
                    models.CharField(max_length=255, verbose_name="opphaveleg filnamn"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="tidsmerke"),
                ),
                (
                    "score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_files",
                        to="sheetmusic.score",
                        verbose_name="note",
                    ),
                ),
            ],
            options={
                "verbose_name": "redigeringsfil",
                "verbose_name_plural": "redigeringsfiler",
                "ordering": ["filename_original"],
            },
        ),
    ]
