# Generated by Django 4.0 on 2021-12-23 13:26

import os
from types import MethodType
import autoslug.fields
from django.db import migrations


def get_base_filename(self):
    """
    Must have a copy of Pdf.get_base_filename here because methods model methods are
    not available in migrations.
    """
    filepath = str(self.file)
    filename = os.path.basename(filepath)
    filename_no_ext = os.path.splitext(filename)[0]
    return filename_no_ext

def populate_pdf_slugs(apps, schema_editor):
    Pdf = apps.get_model("sheetmusic", "Pdf")
    for pdf in Pdf.objects.all():
        if pdf.slug == "nothing":
            # Setting slug to None and calling save will make autoslug generate a new and unique slug
            pdf.slug = None
            pdf.get_base_filename = MethodType(get_base_filename, pdf)
            pdf.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0006_alter_score_created_by_alter_score_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='nothing', editable=True, populate_from=lambda pdf: pdf.get_base_filename(), unique_with=('score__slug',), verbose_name='lenkjenamn'),
            preserve_default=False,
        ),
        migrations.RunPython(populate_pdf_slugs),
    ]
