# Generated by Django 4.1 on 2022-11-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheetmusic", "0007_original"),
    ]

    operations = [
        migrations.AlterField(
            model_name="original",
            name="file",
            field=models.FileField(
                max_length=255, upload_to="sheetmusic/originals/", verbose_name="fil"
            ),
        ),
    ]
