# Generated by Django 3.0.2 on 2021-05-13 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0007_auto_20210512_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='sheetmusic.Pdf'),
        ),
    ]
