# Generated by Django 4.0 on 2021-12-25 14:59

import autoslug.fields
from django.db import migrations

import sheetmusic.models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0007_pdf_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from=sheetmusic.models.pdf_filename_no_extension, unique_with=('score__slug',), verbose_name='lenkjenamn'),
        ),
    ]
