# Generated by Django 4.1 on 2022-11-18 13:16

import common.forms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheetmusic", "0008_alter_original_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="original",
            name="file",
            field=models.FileField(
                max_length=255,
                upload_to="sheetmusic/originals/",
                validators=[
                    common.forms.validators.FileTypeValidator(
                        {"application/octet-stream": [".musx"]}
                    )
                ],
                verbose_name="fil",
            ),
        ),
    ]
