# Generated by Django 4.0 on 2021-12-30 19:28

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0008_alter_pdf_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['name'], 'verbose_name': 'stemme', 'verbose_name_plural': 'stemmer'},
        ),
        migrations.AlterField(
            model_name='pdf',
            name='file',
            field=models.FileField(default=None, max_length=255, upload_to='sheetmusic/original_pdfs/', validators=[common.validators.FileTypeValidator({'application/pdf': ['.pdf'], 'application/x-bzpdf': ['.pdf'], 'application/x-gzpdf': ['.pdf'], 'application/x-pdf': ['.pdf']})], verbose_name='fil'),
        ),
    ]
