# Generated by Django 3.2.8 on 2021-10-28 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0009_remove_userspreferredpart_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['pdf', 'fromPage', 'toPage', 'name']},
        ),
    ]
