# Generated by Django 4.0 on 2022-01-09 08:06

from os.path import basename

from django.db import migrations, models


def ensure_filename_original(apps, schema_editor):
    Pdf = apps.get_model("sheetmusic", "Pdf")
    for pdf in Pdf.objects.all():
        pdf.filename_original = basename(pdf.file.name)
        pdf.save()


class Migration(migrations.Migration):

    dependencies = [
        ("sheetmusic", "0009_alter_part_options_alter_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdf",
            name="filename_original",
            field=models.CharField(
                max_length=255, null=True, verbose_name="opphaveleg filnamn"
            ),
        ),
        migrations.RunPython(ensure_filename_original),
    ]
