# Generated by Django 4.1 on 2022-11-20 12:04

import common.forms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheetmusic", "0009_alter_original_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="original",
            name="file",
            field=models.FileField(
                max_length=255,
                upload_to="sheetmusic/originals/",
                validators=[
                    common.forms.validators.FileTypeValidator(
                        [".mscz", ".mscx", ".niff", ".sib", ".musx"]
                    )
                ],
                verbose_name="fil",
            ),
        ),
        migrations.AlterField(
            model_name="pdf",
            name="file",
            field=models.FileField(
                default=None,
                max_length=255,
                upload_to="sheetmusic/original_pdfs/",
                validators=[common.forms.validators.FileTypeValidator([".pdf"])],
                verbose_name="fil",
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="sound_file",
            field=models.FileField(
                blank=True,
                default="",
                upload_to="sheetmusic/sound_files/",
                validators=[
                    common.forms.validators.FileTypeValidator(
                        [".mp3", ".midi", ".mid", ".ogg", ".mp4", ".m4a", ".flac"]
                    )
                ],
                verbose_name="lydfil",
            ),
        ),
    ]
