# Generated by Django 3.2.8 on 2021-10-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0010_alter_part_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='processing',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
