# Generated by Django 4.0 on 2022-01-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0010_pdf_filename_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='filename_original',
            field=models.CharField(max_length=255, verbose_name='opphaveleg filnamn'),
        ),
    ]
