# Generated by Django 3.2.9 on 2021-11-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0011_alter_pdf_processing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentspreferredpart',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='instrumentspreferredpart',
            name='part',
        ),
        migrations.RemoveField(
            model_name='instrumentspreferredpart',
            name='score',
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['pdf', 'fromPage', 'toPage', 'name'], 'verbose_name': 'stemme', 'verbose_name_plural': 'stemmer'},
        ),
        migrations.AlterModelOptions(
            name='pdf',
            options={'ordering': ['-timestamp'], 'verbose_name': 'pdf', 'verbose_name_plural': 'pdfar'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-timestamp'], 'verbose_name': 'note', 'verbose_name_plural': 'notar'},
        ),
        migrations.AlterModelOptions(
            name='userspreferredpart',
            options={'ordering': ['user', 'part'], 'verbose_name': 'brukarfavorittstemme', 'verbose_name_plural': 'brukarfavorittstemmer'},
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='InstrumentsPreferredPart',
        ),
    ]
