# Generated by Django 4.0 on 2022-01-09 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0011_alter_pdf_filename_original'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdf',
            options={'ordering': ['filename_original'], 'verbose_name': 'pdf', 'verbose_name_plural': 'pdfar'},
        ),
    ]
