# Generated by Django 3.2.9 on 2021-11-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0012_auto_20211104_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['pdf', 'from_page', 'to_page', 'name'], 'verbose_name': 'stemme', 'verbose_name_plural': 'stemmer'},
        ),
        migrations.RenameField(
            model_name='part',
            old_name='fromPage',
            new_name='from_page',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='toPage',
            new_name='to_page',
        ),
    ]
