# Generated by Django 4.0.1 on 2022-01-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0012_alter_pdf_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['title', '-created'], 'verbose_name': 'note', 'verbose_name_plural': 'notar'},
        ),
        migrations.RenameField(
            model_name='score',
            old_name='submitted',
            new_name='created',
        ),
    ]
