# Generated by Django 3.2.9 on 2021-11-26 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sheetmusic', '0013_auto_20211124_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='from_page',
            field=models.IntegerField(default=None, verbose_name='første side'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=255, verbose_name='navn'),
        ),
        migrations.AlterField(
            model_name='part',
            name='pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='sheetmusic.pdf', verbose_name='pdf'),
        ),
        migrations.AlterField(
            model_name='part',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='tidsmerke'),
        ),
        migrations.AlterField(
            model_name='part',
            name='to_page',
            field=models.IntegerField(default=None, verbose_name='siste side'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='file',
            field=models.FileField(default=None, upload_to='sheetmusic/original_pdfs/', validators=[upload_validator.FileTypeValidator(allowed_extensions=['.pdf', '.PDF'], allowed_types=['application/pdf', 'application/x-pdf', 'application/x-bzpdf', 'application/x-gzpdf'])], verbose_name='fil'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='processing',
            field=models.BooleanField(default=False, editable=False, verbose_name='prosessering pågår'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='sheetmusic.score', verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='tidsmerke'),
        ),
        migrations.AlterField(
            model_name='score',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='tidsmerke'),
        ),
        migrations.AlterField(
            model_name='score',
            name='title',
            field=models.CharField(max_length=255, verbose_name='tittel'),
        ),
        migrations.AlterField(
            model_name='userspreferredpart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetmusic.part', verbose_name='stemme'),
        ),
        migrations.AlterField(
            model_name='userspreferredpart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='brukar'),
        ),
    ]
