# Generated by Django 4.0.1 on 2022-01-24 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_alter_instrumentgroup_options_and_more'),
        ('sheetmusic', '0013_alter_score_options_rename_submitted_score_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['instrument_type', 'part_number', 'note']},
        ),
        migrations.RemoveField(
            model_name='part',
            name='name',
        ),
        migrations.AddField(
            model_name='part',
            name='instrument_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='instruments.instrumenttype', verbose_name='instrumenttype'),
        ),
        migrations.AddField(
            model_name='part',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='merknad'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='stemmenummer'),
        ),
    ]
