# Generated by Django 4.0.1 on 2022-01-24 10:44

import autoslug.fields
from django.db import migrations
import django.db.models.expressions
import sheetmusic.models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0015_alter_part_instrument_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['instrument_type', django.db.models.expressions.OrderBy(django.db.models.expressions.F('part_number'), nulls_first=True), 'note']},
        ),
        migrations.AlterField(
            model_name='part',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from=sheetmusic.models.Part.to_string, unique_with=('pdf__score__slug',), verbose_name='lenkjenamn'),
        ),
    ]
