# Generated by Django 4.0.1 on 2022-01-24 10:48

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0016_alter_part_options_alter_part_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['instrument_type', django.db.models.expressions.OrderBy(django.db.models.expressions.F('part_number'), nulls_first=True), 'note'], 'verbose_name': 'stemme', 'verbose_name_plural': 'stemmer'},
        ),
    ]
