# Generated by Django 4.0.1 on 2022-01-25 11:52

from django.db import migrations, models
import django.db.models.expressions


def delete_all_parts(apps, schema_editor):
    """
    Here we simply delte all parts to satisfy the new unique constraint
    """
    Part = apps.get_model("sheetmusic", "Part")
    Part.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0017_alter_part_options'),
    ]

    operations = [
        migrations.RunPython(delete_all_parts),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('pdf'), django.db.models.expressions.F('instrument_type'), django.db.models.expressions.F('part_number'), django.db.models.expressions.F('note'), name='unique_part'),
        ),
    ]
