# Generated by Django 3.2.8 on 2021-11-07 08:44

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='tittel')),
                ('content', models.TextField(verbose_name='innhald')),
                ('submitted', models.DateTimeField(auto_now_add=True, verbose_name='lagt ut')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='redigert')),
                ('start_time', models.DateTimeField(verbose_name='starttid')),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='sluttid')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique_with=('title', 'start_time__year'), verbose_name='slug')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_created', to=settings.AUTH_USER_MODEL, verbose_name='laga av')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_modified', to=settings.AUTH_USER_MODEL, verbose_name='redigert av')),
            ],
            options={
                'verbose_name': 'hending',
                'verbose_name_plural': 'hendingar',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATTENDING', 'Deltek'), ('ATTENDING_MAYBE', 'Deltek kanskje'), ('ATTENDING_NOT', 'Deltek ikkje')], max_length=255, verbose_name='status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='laga')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event', verbose_name='hending')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL, verbose_name='person')),
            ],
            options={
                'verbose_name': 'hendingdeltaking',
                'verbose_name_plural': 'hendingdeltakingar',
            },
        ),
        migrations.AddConstraint(
            model_name='eventattendance',
            constraint=models.UniqueConstraint(fields=('event', 'person'), name='unique_event_attendance'),
        ),
    ]
