# Generated by Django 4.0.3 on 2022-05-22 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventKeyinfoEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, verbose_name="nykel")),
                (
                    "info",
                    models.CharField(blank=True, max_length=1023, verbose_name="info"),
                ),
                (
                    "order",
                    models.FloatField(
                        default=0,
                        help_text="Definerer rekkjefølgja til oppføringar. Oppføringar med lik rekkjefølgje vert sortert etter nykel.",
                        verbose_name="rekkjefølgje",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyinfo_entries",
                        to="events.event",
                        verbose_name="hending",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nykelinfo-oppføring for hending",
                "verbose_name_plural": "Nykelinfo-oppføringar for hending",
                "ordering": ["order", "key"],
            },
        ),
        migrations.AddConstraint(
            model_name="eventkeyinfoentry",
            constraint=models.UniqueConstraint(
                fields=("key", "event"), name="unique_EventKeyinfoEntry"
            ),
        ),
    ]
