# Generated by Django 3.2.8 on 2021-10-24 12:30

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20201020_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time'], 'verbose_name': 'hending', 'verbose_name_plural': 'hendingar'},
        ),
        migrations.AlterModelOptions(
            name='eventattendance',
            options={'verbose_name': 'hendingdeltaking', 'verbose_name_plural': 'hendingdeltakingar'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='owner',
        ),
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.TextField(default='', verbose_name='innhald'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='event_created', to='accounts.usercustom', verbose_name='laga av'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='redigert'),
        ),
        migrations.AddField(
            model_name='event',
            name='modified_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='event_modified', to='accounts.usercustom', verbose_name='redigert av'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=True, populate_from='title', unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='lagt ut'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='sluttid'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(verbose_name='starttid'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='tittel'),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event', verbose_name='hending'),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL, verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='status',
            field=models.CharField(choices=[('ATTENDING', 'Deltek'), ('ATTENDING_MAYBE', 'Deltek kanskje'), ('ATTENDING_NOT', 'Deltek ikkje')], max_length=255, verbose_name='status'),
        ),
    ]
