# Generated by Django 4.1 on 2022-08-24 23:31

import json
from os.path import dirname, join, realpath

from django.db import migrations


def categorize_old_events(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    EventCategory = apps.get_model("events", "EventCategory")
    with open(join(dirname(realpath(__file__)), "hendingskategoriar.json")) as file:
        event_categories = json.load(file)
    for event in Event.objects.all():

        def categorize_event():
            for category_name in event_categories:
                for keyword in event_categories[category_name]:
                    if event.title.lower().find(keyword.lower()) != -1:
                        category, _ = EventCategory.objects.get_or_create(
                            name=category_name
                        )
                        event.category = category
                        event.save()
                        return

        categorize_event()


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_eventcategory_event_category"),
    ]

    operations = [migrations.RunPython(categorize_old_events)]
