# Generated by Django 3.2.8 on 2021-10-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20211024_1430'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventattendance',
            constraint=models.UniqueConstraint(fields=('event', 'person'), name='unique_event_attendance'),
        ),
    ]
