# Generated by Django 4.1 on 2022-08-24 17:45

import django.db.models.deletion
import django_userforeignkey.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0003_alter_event_created_by_alter_event_modified_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="namn"),
                ),
            ],
            options={
                "verbose_name": "hendingskategori",
                "verbose_name_plural": "hendingskategoriar",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="events.eventcategory",
                verbose_name="Kategori",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="created",
            field=models.DateTimeField(verbose_name="lagt ut"),
        ),
        migrations.AlterField(
            model_name="event",
            name="modified",
            field=models.DateTimeField(verbose_name="redigert"),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_by",
            field=django_userforeignkey.models.fields.UserForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="laga av",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="modified_by",
            field=django_userforeignkey.models.fields.UserForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="redigert av",
            ),
        ),
    ]
