# Generated by Django 4.1 on 2022-08-25 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_eventcategory_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="events.eventcategory",
                verbose_name="Kategori",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="lagt ut"),
        ),
        migrations.AlterField(
            model_name="event",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="redigert"),
        ),
    ]
