# Generated by Django 4.0.1 on 2022-01-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventattendance_modified_alter_event_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='submitted',
            new_name='created',
        ),
    ]
