# Generated by Django 3.2.8 on 2021-10-31 17:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventattendance_unique_event_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique_with=('title', 'start_time__year'), verbose_name='slug'),
        ),
    ]
