# Generated by Django 4.0.1 on 2022-01-30 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_submitted_event_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='starttid'),
        ),
    ]
