# Generated by Django 3.2.8 on 2021-11-01 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendance',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='laga'),
            preserve_default=False,
        ),
    ]
