# Generated by Django 4.0.2 on 2022-02-08 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventattendance',
            options={'ordering': ['person__date_joined'], 'verbose_name': 'hendingdeltaking', 'verbose_name_plural': 'hendingdeltakingar'},
        ),
    ]
