# Generated by Django 4.1 on 2022-10-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_alter_eventcategory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=255, verbose_name="stad"),
        ),
        migrations.AddField(
            model_name="event",
            name="location_link",
            field=models.URLField(blank=True, verbose_name="stadlenkje"),
        ),
    ]
