# Generated by Django 4.1 on 2022-10-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheetmusic", "0006_score_transcribed_by"),
        ("repertoire", "0007_alter_repertoire_created_by_and_more"),
        ("events", "0008_alter_eventcategory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="repertoire_extra_scores",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ekstra notar knytt til hendinga.",
                to="sheetmusic.score",
                verbose_name="Ekstra notar",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="repertoires",
            field=models.ManyToManyField(
                blank=True,
                help_text="Repertoar knytt til hendinga.",
                to="repertoire.repertoire",
                verbose_name="Repertoar",
            ),
        ),
    ]
