# Generated by Django 4.1 on 2022-10-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_alter_eventcategory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=255, verbose_name="stad"),
        ),
        migrations.AddField(
            model_name="event",
            name="location_map_link",
            field=models.URLField(
                blank=True,
                help_text="Lenkje til kart over staden hos ei kartteneste som OpenStreetMap, Google Maps eller MazeMap.",
                verbose_name="kartlenkje for stad",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("location", ""), ("location_map_link", "")),
                    models.Q(("location", ""), _negated=True),
                    _connector="OR",
                ),
                name="event_location_map_link_is_blank_if_location_is_blank",
                violation_error_message="Kan ikkje setje kartlenkje utan stad.",
            ),
        ),
    ]
