# Generated by Django 4.1 on 2022-10-13 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repertoire", "0008_alter_repertoireentry_options_repertoire_scores_and_more"),
        ("sheetmusic", "0006_score_transcribed_by"),
        ("events", "0009_event_repertoire_extra_scores_event_repertoires"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="repertoire_include_active",
            field=models.BooleanField(
                default=False,
                help_text='Gjer at "det vanlege" repertoaret vert knytt til hendinga. Det betyr alle repertoar som er aktive på datoen hendinga skjer.',
                verbose_name="inkluder det vanlege repertoaret",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="events.eventcategory",
                verbose_name="kategori",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="repertoire_extra_scores",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ekstra notar knytt til hendinga.",
                to="sheetmusic.score",
                verbose_name="ekstra notar",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="repertoires",
            field=models.ManyToManyField(
                blank=True,
                help_text="Repertoar knytt til hendinga.",
                to="repertoire.repertoire",
                verbose_name="repertoar",
            ),
        ),
    ]
