# Generated by Django 4.1 on 2023-02-18 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0007_instrumenttypedetectionkeyword_and_more"),
        ("events", "0011_event_connected_gallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventattendance",
            name="instrument_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_attendances",
                to="instruments.instrumenttype",
                verbose_name="instrumenttype",
            ),
        ),
    ]
