# Generated by Django 3.2.7 on 2021-09-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title'], 'verbose_name': 'artikkel', 'verbose_name_plural': 'artiklar'},
        ),
    ]
