# Generated by Django 3.0.2 on 2021-08-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='public',
            field=models.BooleanField(default=False, help_text='Om artikkelen er open for ålmente.', verbose_name='offentleg'),
        ),
    ]
