# Generated by Django 3.0.2 on 2021-08-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments_allowed',
            field=models.BooleanField(default=True, verbose_name='open for kommentarar'),
        ),
    ]
