# Generated by Django 3.0.2 on 2021-09-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210827_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title']},
        ),
    ]
