# Generated by Django 4.0.1 on 2022-01-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_content_alter_article_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='submitted',
            new_name='created',
        ),
    ]
