# Generated by Django 4.0.1 on 2022-02-04 08:10

import autoslug.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='lagt ut')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='redigert')),
                ('title', models.CharField(max_length=255, verbose_name='tittel')),
                ('content', models.TextField(blank=True, verbose_name='innhald')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='dato')),
                ('file', models.FileField(blank=True, default=None, upload_to='minutes/', verbose_name='fil')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique=True, verbose_name='lenkjenamn')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='laga av')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='redigert av')),
            ],
            options={
                'verbose_name': 'referat',
                'verbose_name_plural': 'referat',
                'ordering': ['-created'],
            },
        ),
    ]
