# Generated by Django 4.0.4 on 2022-06-10 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("minutes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="minutes",
            options={
                "ordering": ["-date"],
                "verbose_name": "referat",
                "verbose_name_plural": "referat",
            },
        ),
    ]
