# Generated by Django 4.0.1 on 2022-02-03 13:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique=True, verbose_name='lenkjenamn'),
        ),
    ]
