# Generated by Django 4.0.2 on 2022-03-02 07:34

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('user_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': [django.db.models.functions.text.Lower('name')], 'verbose_name': 'brukarfil', 'verbose_name_plural': 'brukarfiler'},
        ),
    ]
