# Generated by Django 4.0.3 on 2022-05-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='public',
            field=models.BooleanField(default=False, verbose_name='offentleg'),
        ),
    ]
