# Generated by Django 4.0.3 on 2022-05-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_files", "0002_file_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="public",
            field=models.BooleanField(
                default=False,
                help_text="Om fila er open for ålmente.",
                verbose_name="offentleg",
            ),
        ),
    ]
