# Generated by Django 4.0 on 2021-12-27 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_usercustom_jacket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.DateTimeField(auto_now_add=True, verbose_name='lagt ut')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='redigert')),
                ('question', models.CharField(max_length=255, verbose_name='spørsmål')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to='accounts.usercustom', verbose_name='laga av')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified', to='accounts.usercustom', verbose_name='redigert av')),
            ],
            options={
                'verbose_name': 'avstemming',
                'verbose_name_plural': 'avstemmingar',
                'ordering': ['-submitted'],
            },
        ),
    ]
