# Generated by Django 4.0 on 2022-01-05 13:28

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_remove_usercustom_jacket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='val')),
            ],
            options={
                'verbose_name': 'val',
                'verbose_name_plural': 'val',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='lagt ut')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.choice', verbose_name='val')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='accounts.usercustom', verbose_name='brukar')),
            ],
            options={
                'verbose_name': 'stemme',
                'verbose_name_plural': 'stemmer',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.DateTimeField(auto_now_add=True, verbose_name='lagt ut')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='redigert')),
                ('question', models.CharField(max_length=255, verbose_name='spørsmål')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='question', unique=True, verbose_name='lenkjenamn')),
                ('public', models.BooleanField(default=False, help_text='Om avstemminga er open for ålmente.', verbose_name='offentleg')),
                ('type', models.CharField(choices=[('SINGLE_CHOICE', 'Eitt val'), ('MULTIPLE_CHOICE', 'Fleirval')], default='SINGLE_CHOICE', max_length=255, verbose_name='type')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to='accounts.usercustom', verbose_name='laga av')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified', to='accounts.usercustom', verbose_name='redigert av')),
            ],
            options={
                'verbose_name': 'avstemming',
                'verbose_name_plural': 'avstemmingar',
                'ordering': ['-submitted'],
                'get_latest_by': 'submitted',
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.poll', verbose_name='avstemming'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('choice', 'user'), name='one_vote_per_user_per_choice'),
        ),
    ]
