# Generated by Django 4.0 on 2021-12-27 08:07

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=True, populate_from='question', unique=True, verbose_name='lenkjenamn'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=50, verbose_name='spørsmål'),
        ),
    ]
