# Generated by Django 4.0 on 2021-12-27 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usercustom_jacket'),
        ('polls', '0003_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='public',
            field=models.BooleanField(default=False, help_text='Om avstemminga er open for ålmente.', verbose_name='offentleg'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.choice', verbose_name='val')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='accounts.usercustom', verbose_name='brukar')),
            ],
            options={
                'verbose_name': 'stemme',
                'verbose_name_plural': 'stemmer',
            },
        ),
    ]
