# Generated by Django 4.0 on 2021-12-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_poll_public_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='type',
            field=models.CharField(choices=[('SINGLE_CHOICE', 'Einval'), ('MULTIPLE_CHOICE', 'Fleirval')], default='SINGLE_CHOICE', max_length=255, verbose_name='type'),
        ),
    ]
