# Generated by Django 4.0 on 2021-12-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_poll_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('choice', 'user'), name='one_vote_per_user_per_choice'),
        ),
    ]
