# Generated by Django 4.0 on 2021-12-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_vote_one_vote_per_user_per_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'get_latest_by': 'submitted', 'ordering': ['-submitted'], 'verbose_name': 'avstemming', 'verbose_name_plural': 'avstemmingar'},
        ),
    ]
