# Generated by Django 4.0 on 2021-12-31 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_poll_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-created'], 'verbose_name': 'stemme', 'verbose_name_plural': 'stemmer'},
        ),
        migrations.AddField(
            model_name='vote',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='lagt ut'),
            preserve_default=False,
        ),
    ]
