# Generated by Django 4.0 on 2021-12-31 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_vote_options_vote_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'stemme', 'verbose_name_plural': 'stemmer'},
        ),
    ]
