# Generated by Django 4.1 on 2023-01-23 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="lagt ut"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="redigert"),
                ),
                ("price", models.IntegerField(verbose_name="pris")),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="kommentar"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("PURCHASE", "Kjøp"), ("DEPOSIT", "Innbetaling")],
                        max_length=30,
                        verbose_name="medlemsstatus",
                    ),
                ),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="laga av",
                    ),
                ),
                (
                    "modified_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="redigert av",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brewing_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="brukar",
                    ),
                ),
            ],
            options={
                "verbose_name": "transaksjon",
                "verbose_name_plural": "transaksjonar",
            },
        ),
    ]
