# Generated by Django 4.1 on 2023-01-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brewing", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("price__gt", 0), ("type", "DEPOSIT")),
                    models.Q(("price__lt", 0), ("type", "PURCHASE")),
                    _connector="OR",
                ),
                name="brew_purchases_must_be_negative",
                violation_error_message="Kjøp av brygg må vere negativ.",
            ),
        ),
    ]
