# Generated by Django 4.1 on 2023-03-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brewing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brew",
            name="empty",
            field=models.BooleanField(
                default=False,
                help_text="Om brygget har vorte drukke opp.",
                verbose_name="tomt",
            ),
        ),
        migrations.AddConstraint(
            model_name="brew",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("available_for_purchase", True), ("empty", True), _negated=True
                ),
                name="empty_brews_cannot_be_available_for_purchase",
                violation_error_message="Tomme brygg kan ikkje vere tilgjengelege for kjøp.",
            ),
        ),
    ]
