# Generated by Django 4.1 on 2023-01-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brewing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["created"],
                "verbose_name": "transaksjon",
                "verbose_name_plural": "transaksjonar",
            },
        ),
    ]
