# Generated by Django 4.1 on 2023-02-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brewing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brew",
            name="FG",
            field=models.FloatField(
                blank=True,
                help_text="Final Gravity. Tettleiken av sukker i brygget etter gjæring. Brukt for å berekne alkoholprosent.",
                null=True,
                verbose_name="FG",
            ),
        ),
        migrations.AddField(
            model_name="brew",
            name="OG",
            field=models.FloatField(
                blank=True,
                help_text="Original Gravity. Tettleiken av sukker i brygget før gjæring. Brukt for å berekne alkoholprosent",
                null=True,
                verbose_name="OG",
            ),
        ),
    ]
