# Generated by Django 4.1 on 2023-02-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brewing", "0002_brew_fg_brew_og"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brew",
            name="OG",
            field=models.FloatField(
                blank=True,
                help_text="Original Gravity. Tettleiken av sukker i brygget før gjæring. Brukt for å berekne alkoholprosent.",
                null=True,
                verbose_name="OG",
            ),
        ),
    ]
