# Generated by Django 4.1 on 2023-01-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brewing", "0002_transaction_brew_purchases_must_be_negative"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("PURCHASE", "Kjøp"), ("DEPOSIT", "Innbetaling")],
                max_length=30,
                verbose_name="type",
            ),
        ),
    ]
