# Generated by Django 4.1 on 2023-01-30 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("brewing", "0003_brew_brew_price_per_litre_must_be_positive"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="brew",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="brewing.brew",
                verbose_name="brygg",
            ),
        ),
    ]
