# Generated by Django 4.1 on 2023-01-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brewing", "0003_alter_transaction_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="transaction",
            name="brew_purchases_must_be_negative",
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("price__gt", 0), ("type", "DEPOSIT")),
                    models.Q(("price__lt", 0), ("type", "PURCHASE")),
                    _connector="OR",
                ),
                name="brew_purchases_must_be_negative",
                violation_error_message="Innbetalingar må ha ein positiv pris, kjøp må ha ein negativ pris.",
            ),
        ),
    ]
