# Generated by Django 4.1 on 2023-02-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brewing", "0003_alter_brew_og"),
    ]

    operations = [
        migrations.AddField(
            model_name="brew",
            name="logo",
            field=models.ImageField(
                blank=True, upload_to="brewing/logos", verbose_name="logo"
            ),
        ),
    ]
