# Generated by Django 4.1 on 2023-01-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brewing", "0004_transaction_brew"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-created"],
                "verbose_name": "transaksjon",
                "verbose_name_plural": "transaksjonar",
            },
        ),
        migrations.RemoveConstraint(
            model_name="brew",
            name="brew_price_per_litre_must_be_positive",
        ),
        migrations.AlterField(
            model_name="brew",
            name="price_per_litre",
            field=models.IntegerField(blank=True, null=True, verbose_name="literpris"),
        ),
        migrations.AddConstraint(
            model_name="brew",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("price_per_litre__gt", 0),
                    ("price_per_litre", None),
                    _connector="OR",
                ),
                name="brew_price_per_litre_must_be_positive",
                violation_error_message="Literprisen til eit brygg må vere positiv.",
            ),
        ),
        migrations.AddConstraint(
            model_name="brew",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("available_for_purchase", True),
                    ("price_per_litre", None),
                    _negated=True,
                ),
                name="brew_price_required_if_available_for_purchase",
                violation_error_message="Literpris er påkravd om brygget skal vere tilgjengeleg for kjøp.",
            ),
        ),
    ]
