# Generated by Django 4.1 on 2023-02-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brewing", "0005_alter_transaction_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brew",
            options={
                "get_latest_by": "created",
                "ordering": ["name"],
                "verbose_name": "brygg",
                "verbose_name_plural": "brygg",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "get_latest_by": "created",
                "ordering": ["-created"],
                "verbose_name": "transaksjon",
                "verbose_name_plural": "transaksjonar",
            },
        ),
    ]
