# Generated by Django 4.1 on 2023-01-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brewing", "0006_alter_brew_price_per_litre"),
    ]

    operations = [
        migrations.AddField(
            model_name="brew",
            name="available_for_purchase",
            field=models.BooleanField(
                default=False, verbose_name="tilgjengeleg for kjøp"
            ),
        ),
    ]
