# Generated by Django 3.0.2 on 2021-09-10 19:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='username', verbose_name='slug'),
        ),
    ]
