# Generated by Django 4.0.2 on 2022-02-12 11:45

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='instrument_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='instruments.instrumenttype', verbose_name='instrumenttype'),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='usercustom',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='username_case_insensitive'),
        ),
    ]
