# Generated by Django 3.0.2 on 2021-09-10 19:24

from django.db import migrations


def ensure_slug(apps, schema_editor):
    # We can't import the UserCustom model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    UserCustom = apps.get_model('accounts', 'UserCustom')
    for user in UserCustom.objects.all():
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usercustom_slug'),
    ]

    operations = [
        migrations.RunPython(ensure_slug),
    ]
