# Generated by Django 4.0 on 2022-03-08 20:12

from django.db import migrations


def active_to_paying(apps, schema_editor):
    # We can't import the UserCustom model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    UserCustom = apps.get_model("accounts", "UserCustom")
    UserCustom.objects.filter(membership_status="ACTIVE").update(
        membership_status="PAYING"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_usercustom_membership_status"),
    ]

    operations = [migrations.RunPython(active_to_paying)]
