# Generated by Django 3.0.2 on 2021-09-10 19:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210910_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='username', unique=True, verbose_name='slug'),
        ),
    ]
