# Generated by Django 3.2.7 on 2021-09-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210910_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
