# Generated by Django 3.2.7 on 2021-09-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210910_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='last_name',
        ),
        migrations.AddField(
            model_name='usercustom',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='navn'),
        ),
    ]
