# Generated by Django 3.2.8 on 2021-10-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usercustom_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='last_name',
        ),
        migrations.AddField(
            model_name='usercustom',
            name='address',
            field=models.TextField(blank=True, verbose_name='adresse'),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='profilbilde'),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='fødselsdato'),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='home_page',
            field=models.URLField(blank=True, max_length=255, verbose_name='heimeside'),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='membership_period',
            field=models.CharField(blank=True, help_text='Årstal, semester - Årstal, semester. Til dømes "2005, Haust - 2009, Vår" eller "2009, Haust -"', max_length=255, verbose_name='medlemsperiode'),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='membership_status',
            field=models.CharField(choices=[('ACTIVE', 'Aktiv'), ('INACTIVE', 'Inaktiv'), ('RETIRED', 'Pensjonist'), ('HONORARY', 'Æresmedlem')], default='ACTIVE', max_length=30, verbose_name='medlemsstatus'),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='navn'),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='telefonnummer'),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='student_card_number',
            field=models.CharField(blank=True, help_text='Nummeret på studentkortet ditt. Skriv det inn om du vil ha tilgang til lageret. Nummeret er det som byrjar med EM.', max_length=255, verbose_name='studentkort-nummer'),
        ),
    ]
