# Generated by Django 3.2.7 on 2021-09-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210912_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='membership_status',
            field=models.CharField(choices=[('ACTIVE', 'Aktiv'), ('INACTIVE', 'Inaktiv'), ('RETIRED', 'Pensjonist'), ('SUPPORT', 'Støttemedlem'), ('HONORARY', 'Æresmedlem')], default='ACTIVE', max_length=30),
        ),
    ]
