# Generated by Django 3.2.7 on 2021-09-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usercustom_membership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='membership_period',
            field=models.CharField(blank=True, help_text='Årstal, semester - Årstal, semester. Til dømes "2005, Haust - 2009, Vår" eller "2009, Haust -"', max_length=255, verbose_name='Medlemsperiode'),
        ),
    ]
