# Generated by Django 3.2.9 on 2021-11-30 23:39

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211023_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='username', unique=True, verbose_name='lenkjenamn'),
        ),
    ]
