# Generated by Django 4.0.3 on 2022-04-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usercustom_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='images_social_media',
            field=models.CharField(choices=[('YES', 'Ja'), ('GROUP_ONLY', 'Berre gruppebilete'), ('NO', 'Nei'), ('UNKNOWN', 'Ukjent')], default='UNKNOWN', help_text='Om bilete av deg kan delast på sosiale medier.', max_length=30, verbose_name='bilete på sosiale medier'),
        ),
    ]
