# Generated by Django 3.2.9 on 2021-12-08 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
        ('accounts', '0007_alter_usercustom_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='instrument_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='instruments.instrumentgroup', verbose_name='instrumentgruppe'),
        ),
    ]
