# Generated by Django 3.2.9 on 2021-12-07 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
        ('accounts', '0007_alter_usercustom_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='instrument_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='instruments.instrumenttype', verbose_name='instrumentgruppe'),
        ),
    ]
