# Generated by Django 4.0.3 on 2022-04-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usercustom_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercustom',
            options={'permissions': (('view_storage_access', 'Kan sjå lagertilgjenge'), ('edit_storage_access', 'Kan redigere lagertilgjenge')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
