# Generated by Django 3.2.7 on 2021-09-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210916_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='profilbilde'),
        ),
    ]
