# Generated by Django 4.0.3 on 2022-04-20 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usercustom_images_social_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercustom',
            options={'permissions': (('view_storage_access', 'Kan sjå lagertilgjenge'), ('edit_storage_access', 'Kan redigere lagertilgjenge'), ('view_images_social_media', 'Kan sjå biletesamtykke')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
