# Generated by Django 3.2.9 on 2021-12-07 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usercustom_instrument_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustom',
            old_name='instrument_type',
            new_name='instrument_group',
        ),
    ]
