# Generated by Django 3.2.10 on 2021-12-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usercustom_instrument_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to='profile/', verbose_name='profilbilde'),
            preserve_default=False,
        ),
    ]
