# Generated by Django 4.0.3 on 2022-05-20 21:45

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_usercustom_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='calendar_feed_only_upcoming',
            field=models.BooleanField(default=True, verbose_name='Få kun framtidige hendingar i kalenderfeed'),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='calendar_feed_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Startdato for kalenderfeed'),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='calendar_feed_token',
            field=models.CharField(default=secrets.token_urlsafe, max_length=255, unique=True, verbose_name='Kalenderfeedtoken'),
        ),
    ]
