# Generated by Django 4.0 on 2021-12-18 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniforms', '0001_initial'),
        ('accounts', '0009_alter_usercustom_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='jacket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='uniforms.jacket', verbose_name='jakkenummer'),
        ),
    ]
