# Generated by Django 4.0.3 on 2022-04-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_usercustom_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercustom',
            options={'permissions': (('view_storage_access', 'Kan sjå lagertilgjenge'), ('edit_storage_access', 'Kan redigere lagertilgjenge'), ('view_image_sharing_consent', 'Kan sjå samtykkje til deling av bilete')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='images_social_media',
        ),
        migrations.AddField(
            model_name='usercustom',
            name='image_sharing_consent',
            field=models.CharField(choices=[('YES', 'Ja'), ('GROUP_ONLY', 'Berre gruppebilete'), ('NO', 'Nei'), ('UNKNOWN', 'Ukjent')], default='UNKNOWN', help_text='Om bilete av deg kan delast på sosiale medier.', max_length=30, verbose_name='samtykkje til deling av bilete'),
        ),
    ]
