# Generated by Django 3.2.8 on 2021-10-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_usercustom_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustom',
            old_name='picture',
            new_name='avatar',
        ),
    ]
