# Generated by Django 4.0 on 2021-12-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usercustom_jacket'),
        ('uniforms', '0003_migrate_jacketusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='jacket',
        ),
    ]
