# Generated by Django 4.0.3 on 2022-05-31 13:17

import secrets

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_usercustom_calendar_feed_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercustom",
            name="calendar_feed_start_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="startdato for kalenderapp-integrasjon",
            ),
        ),
        migrations.AlterField(
            model_name="usercustom",
            name="calendar_feed_token",
            field=models.CharField(
                default=secrets.token_urlsafe,
                editable=False,
                max_length=255,
                unique=True,
                verbose_name="kalenderapp-integrasjonstoken",
            ),
        ),
    ]
