# Generated by Django 4.0 on 2022-01-07 07:33

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_usercustom_jacket'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usercustom',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='username_case_insensitive'),
        ),
    ]
