# Generated by Django 4.0.4 on 2022-06-23 16:52

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_usercustom_calendar_feed_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='calendar_feed_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='startdato for kalenderintegrasjon'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='calendar_feed_token',
            field=models.CharField(default=secrets.token_urlsafe, editable=False, max_length=255, unique=True, verbose_name='kalenderintegrasjonstoken'),
        ),
    ]
