# Generated by Django 4.0.1 on 2022-01-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_alter_instrumentgroup_options_and_more'),
        ('accounts', '0012_usercustom_username_case_insensitive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='instrument_group',
        ),
        migrations.AddField(
            model_name='usercustom',
            name='instrument_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='instruments.instrumenttype', verbose_name='instrumenttype'),
        ),
    ]
