# Generated by Django 4.1 on 2022-08-03 15:18

import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_usercustom_calendar_feed_start_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usercustom",
            options={
                "ordering": [
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.NullIf(
                            "name", models.Value("")
                        ),
                        nulls_last=True,
                    )
                ],
                "permissions": (
                    ("view_storage_access", "Kan sjå lagertilgjenge"),
                    ("edit_storage_access", "Kan redigere lagertilgjenge"),
                    (
                        "view_image_sharing_consent",
                        "Kan sjå samtykkje til deling av bilete",
                    ),
                ),
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
