# Generated by Django 4.1 on 2022-08-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_orchestras", "0001_initial"),
        ("accounts", "0015_alter_usercustom_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercustom",
            name="orchestras",
            field=models.ManyToManyField(
                blank=True,
                help_text="Andre studentorchester som du er medlem av",
                to="external_orchestras.orchestra",
                verbose_name="andre orchestermedlemskap",
            ),
        ),
    ]
