# Generated by Django 4.1 on 2022-11-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_usercustom_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercustom",
            name="can_wear_hats",
            field=models.BooleanField(
                default=None,
                help_text="Har tatt opptaket, og kan difor bruka hattar, og treng ikkje bruka aluminiumsfoliehatt",
                null=True,
                verbose_name="kan bruka hattar",
            ),
        ),
    ]
