# Generated by Django 4.1 on 2023-04-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_alter_usercustom_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercustom",
            name="is_active_override",
            field=models.BooleanField(
                default=False,
                help_text="Overstyrer om eit medlem vert sett på som aktivt. Mellombels løysing fram til statuttane er oppklåra.",
                verbose_name="overstyring av aktiv status",
            ),
        ),
    ]
