# Generated by Django 4.1 on 2023-04-03 11:41

import autoslug.fields
import django.db.models.deletion
import django.utils.timezone
import django_userforeignkey.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mascot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="lagt ut"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="redigert"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="namn")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="pictures/", verbose_name="bilete"
                    ),
                ),
                (
                    "creationStartDate",
                    models.DateField(
                        blank=True,
                        help_text="Når starta laginga av maskoten?",
                        verbose_name="startdato",
                    ),
                ),
                (
                    "creationEndDate",
                    models.DateField(
                        blank=True,
                        help_text="Når ble maskoten ferdig?",
                        verbose_name="sluttdato",
                    ),
                ),
                (
                    "passord",
                    models.CharField(
                        blank=True,
                        help_text="Dette finner dykk eit stad på maskoten.",
                        max_length=255,
                        verbose_name="passord",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=True,
                        populate_from="name",
                        unique=True,
                        verbose_name="lenkjenamn",
                    ),
                ),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="laga av",
                    ),
                ),
                (
                    "creators",
                    models.ManyToManyField(
                        to=settings.AUTH_USER_MODEL, verbose_name="creator"
                    ),
                ),
                (
                    "modified_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="redigert av",
                    ),
                ),
            ],
            options={
                "verbose_name": "maskot",
                "verbose_name_plural": "maskoter",
            },
        ),
        migrations.CreateModel(
            name="SalvageDiaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="titel")),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="tidspunkt"
                    ),
                ),
                (
                    "thieves",
                    models.CharField(
                        help_text="Kvem er dykk?",
                        max_length=255,
                        verbose_name="bergere",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="salvage_diary/pictures",
                        verbose_name="bilete",
                    ),
                ),
                (
                    "story",
                    models.TextField(
                        blank=True,
                        help_text="Kva skjedde? Korleis berga dykk den? Kva har dykk endra?",
                        verbose_name="Historie",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        blank=True,
                        help_text="Når skjedde dette? SMASH? TORSK? Medaljegalla?",
                        max_length=255,
                        verbose_name="hending",
                    ),
                ),
                (
                    "mascot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salvageEntries",
                        to="salvage_diary.mascot",
                        verbose_name="maskot",
                    ),
                ),
            ],
            options={
                "verbose_name": "bergedagbokinnlegg",
                "verbose_name_plural": "bergedagbokinnlegg",
            },
        ),
    ]
