name: Pull new commits from Taktlausveven

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  pull_and_create_pr:
    runs-on: ubuntu-latest
    outputs:
      repository_changed
    steps:
      - uses: actions/checkout@v3

      - name: Pull changes
        id: pull
        run: |
          cd website_build
            git remote add taktlausveven https://gitlab.com/taktlause/taktlausveven.git
            git merge taktlausveven/main
            if [ $(git fetch --dry-run) != "" ]
            then
              echo "new_changes=1" >> "$GITHUB_OUTPUT"
            else
              echo "new_changes=0" >> "$GITHUB_OUTPUT"
            fi
          cd ..
      
      - name: Create Pull Request
        if: steps.pull.outputs.new_changes == "1"
        uses: peter-evans/create-pull-request@v5
        with:
          committer: Mergeman <mergeman@mytaktlausvev.no>
          author: Mergeman <mergeman@mytaktlausvev.no>
          branch: pull-taktlausveven
          reviewers: sigurdo
